version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - proxy
    environment:
      VIRTUAL_HOST: monitoring.classroom.dkr

  rethinkdb:
    image: rethinkdb
    ports:
      - 8080:8080
      - 28015:28015
    volumes:
      - storage:/data
    depends_on:
      - proxy
    environment:
      VIRTUAL_HOST: db.classroom.dkr
    networks:
      default:
        aliases:
          - db.classroom

  api:
    build:
      context: ./api
    image: classroom:api
    depends_on:
      - proxy
      - rethinkdb
    expose:
      - 80
    networks:
      - default
    environment:
      VIRTUAL_HOST: api.classroom.dkr

  socket:
    build:
      context: ./socket
    image: classroom:socket
    depends_on:
      - proxy
      - rethinkdb
    expose:
      - 80
    networks:
      - default
    environment:
      VIRTUAL_HOST: socket.classroom.dkr

  web:
    build:
      context: ./web
    image: classroom:web
    depends_on:
      - proxy
    expose:
      - 80
    networks:
      - default
    environment:
      VIRTUAL_HOST: web.classroom.dkr

volumes:
  storage:
    driver: local
networks:
  default:
    external:
      name: classroom